# Generated by Django 5.2.11 on 2026-03-06 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History'), ('biography', 'Biography'), ('other', 'other')], default='fiction', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(help_text='Enter a 4-digit year (e.g., 2026)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
